name: GitHub Actions

on:
  push:
    branches: [master]
  pull_request:
    branches: ['**']

jobs:
  deploy_gh_pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          cd vite-with-i18n
          npm ci

      - name: Build
        run: |
          cd vite-with-i18n
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vite-with-i18n/dist
          publish_branch: gh-pages
