name: GitHub Actions
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch on Push and any branches on PR
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [22]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: |
          cd webpack-bs5-demo-with-locales
          yarn install

      - name: Bootstrap 5 Prod Build for GitHub demo website
        run: |
          cd webpack-bs5-demo-with-locales
          yarn run build

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webpack-bs5-demo-with-locales/dist
